### ISSUE TITLE
TypeError: Path must be a string with TFS 2017

### ISSUE THREAD

**Issue by mrpolaris** [StefanKert/azuredevops-codesigning-task#4]
Working with TFS 2017 Update 3 I get the error below.

Seems it does not resolve something.

TypeError: Path must be a string. Received undefined
at assertPath (path.js:7:11)
at Object.resolve (path.js:186:7)
at Object.resolve (E:\BuildAgent\Agent3\_work\_tasks\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\1.1.0\node_modules\vsts-task-lib\task.js:581:37)
 at SecureFileDownloader.getSecureFileTempDownloadPath (E:\BuildAgent\Agent3\_work\_tasks\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\1.1.0\securefiledownloader.js:47:35)
##[debug]task result: Failed
at SecureFileDownloader.<anonymous> (E:\BuildAgent\Agent3\_work\_tasks\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\1.1.0\securefiledownloader.js:24:42)
at next (native)
at E:\BuildAgent\Agent3\_work\_tasks\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\1.1.0\securefiledownloader.js:7:71
at __awaiter (E:\BuildAgent\Agent3\_work\_tasks\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\1.1.0\securefiledownloader.js:3:12)
at SecureFileDownloader.downloadSecureFile (E:\BuildAgent\Agent3\_work\_tasks\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\1.1.0\securefiledownloader.js:23:16)
 at E:\BuildAgent\Agent3\_work\_tasks\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\1.1.0\index.js:33:54

**Comment by mrpolaris** [comment]
This task seems to work on the build pipelines but does not work in the release pipelines

**Comment by StefanKert** [comment]
I have not yet tried this with release tasks. Are you still facing this issue?

**Comment by mrpolaris** [comment]
Yes  seems the variable between the build and the release pipelines are different

**Comment by StefanKert** [comment]
I will check that out and let you know if I can provide a fix.

**Comment by StefanKert** [comment]
I tried to run this task in a release process and everything worked out as expected. Maybe it is related to the new 2.0.0 which I released today. If you have time I´d really appreciate it if you could test this with the new version.

**Comment by StefanKert** [comment]
Since the latest version should work I will close this issue. Please reopen if it is not working.
